# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
	  # specify the version you desire here
	  - image: circleci/node:8.12

jobs:
	build:
	<<: *defaults  

	steps:
	  # Download and cache dependencies
	  - checkout # special step to check out source code to working directory
	  - run:
		  name: update-npm
		  command: 'sudo npm install -g npm@latest'
	  - restore_cache: # special step to restore the dependency cache
		  # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
		  key: dependency-cache-{{ checksum "package.json" }}
	  - run:
		  name: install-npm
		  command: npm install
	  - save_cache: # special step to save the dependency cache
		  key: dependency-cache-{{ checksum "package.json" }}
		  paths:
			- ./node_modules

	  # - run:
	  #     name: build
	  #     command: npm run build

	  # - run: # run tests
	  #     name: test
	  #     command: npm test

	  - run:
		  name: Authenticate with registry
		  command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc

	  - run:
		  name: package bump
		  command: npm version patch -f
	  - run:
		  name: publish package
		  command: npm publish