# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts

# Useful tutorial:
# https://www.matcha440.net/posts/npm-ci-cd-with-azure-pipelines/

pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.15.3'

  - script: |
      yarn install
    displayName: 'Install'
  
  - script: |
      yarn build
    displayName: 'Build'

  - script: |
      yarn test:ci
    displayName: 'Test'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/TEST-RESULTS.xml'
      testRunTitle: 'Test results for JavaScript'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs: 
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/.tmp/coverage/cobertura-coverage.xml'
      # cobertura-coverage.xml 
      reportDirectory: '$(System.DefaultWorkingDirectory)/.tmp/coverage'
      
  # - task: ArchiveFiles@2
  #   inputs:
  #     rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
  #     includeRootFolder: false

  # - task: PublishBuildArtifacts@1

  - task: Npm@1
    inputs:
      command: publish
      publishEndpoint: 'npm'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master')) #refs/tags/
    displayName: 'Publish to NPM'



  # - script: |
  #     npm install
  #     npm test
  #     docker build -f Dockerfile -t $(dockerId).azurecr.io/$(imageName) .
  #     docker login -u $(dockerId) -p $pswd $(dockerId).azurecr.io
  #     docker push $(dockerId).azurecr.io/$(imageName)
  #   env:
  #     pswd: $(dockerPassword) 