# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts

# Useful tutorial:
# https://www.matcha440.net/posts/npm-ci-cd-with-azure-pipelines/

pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.15.3'

  - script: npm install
    
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: install
  
  - script: |
      yarn build
    displayName: 'build'

  - script: yarn test
    displayName: Test

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/TEST-RESULTS.xml'
      testRunTitle: 'Test results for JavaScript'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs: 
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
      
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1

  # - script: |
  #     npm install
  #     npm test
  #     docker build -f Dockerfile -t $(dockerId).azurecr.io/$(imageName) .
  #     docker login -u $(dockerId) -p $pswd $(dockerId).azurecr.io
  #     docker push $(dockerId).azurecr.io/$(imageName)
  #   env:
  #     pswd: $(dockerPassword) 

  - task: Npm@1
    inputs:
      command: publish
      publishEndpoint: 'npm'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'Publish to NPM'
