# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        if: "!contains(github.event.head_commit.message, 'skip-ci')"

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            # - uses: actions/checkout@master
            - uses: actions/checkout@v2
            - uses: oven-sh/setup-bun@v1

            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@octocat' # Defaults to the user or organization that owns the workflow file:
            - run: bun install
            - run: bun build
            - run: bun test:ci
            - run: bun bundle
            - name: bun bump
              if: github.ref == 'refs/heads/master'
              run: |
                  git config user.email "elya.livshitz@gmail.com"
                  git config user.name "Elya Livshitz"
                  bun bump
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
                  file: .tmp/coverage/cobertura-coverage.xml # optional
                  # files: ./coverage1.xml,./coverage2.xml # optional
                  # flags: unittests # optional
                  # name: codecov-umbrella # optional
                  # fail_ci_if_error: true # optional (default = false)
                  verbose: true # optional (default = false)
